decentraland/explorer-website

- src/kernel-loader/injector.ts
fix: remove `?cors` from request to work directly with a static file server like S3
> fix: remove `?cors` from request

- public/index.html
This PR solves #146 by adding open graph meta tags
Twitter:
Facebook:
Just copy and pate the url on the following official validators:
[https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)
[https://developers.facebook.com/tools/debug/](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fexplorer-artifacts.decentraland.org%2F%40dcl%2Fexplorer-website%2Fbranch%2Ffix%2Fopen-graph%2F%3Fkernel-branch%3Dmain%26renderer-branch%3Dmaster)
or send the build url using any message app that send previews
> fix: add open graph meta tags

- src/index.tsx
- src/utils/clearWalletConnect.ts
In order to prevent wallet connect from trying to reconnect each time the user enters the application, both the `walletconnect` and `decentraland-connect-storage-key` (when provider type is wallet_connect) are being removed from local storage.
Removing `walletconnect` will prevent the app to bypass the QR when the user is already connected with the wallet.
Removing `decentraland-connect-storage-key` will prevent the QR to be automatically shown when the user enters the app again.
> chore: Remove Wallet Connect data on init

- package-lock.json
- package.json
Update decentraland renderer to have the latest UI version of the explorer in local.
| before | after |
|---------|--------|
| ![Screen Shot 2022-04-01 at 15 27 09](https://user-images.githubusercontent.com/208789/161321450-fb044ac8-8d9f-4cb0-bc39-1f7eb736086e.jpg) | ![Screen Shot 2022-04-01 at 15 24 41](https://user-images.githubusercontent.com/208789/161321437-6d904b61-ddc5-4c89-a1a9-4fb896752c83.jpg) |
> chore: update decentraland-ecs

- src/integration/browser.ts
- src/integration/desktop.ts
- src/kernel-loader/index.ts
> This PR solves #183
It remember the last time a user authenticates into the browser version and prevent the desktop launch if it has pass less than a week
- you need to have the desktop version install in your computer
- open the test link 
- you will be prompted to open the desktop version
- cancel it
- log in to Decentraland in your browser
- reload the page
- you should be prompted again
- session should start automatically
> feat: prevent desktop launch for recently logged in users

- src/components/App.css
- src/components/auth/EthWalletSelector.tsx
- src/components/auth/LoginContainer.tsx
- src/components/auth/LoginItemContainer.tsx
Solves: #198
Users (mainly on desktop) report that some time they are not able to connect because wallet-connect never ask for a sign to complete the login, and they stay in the first loading page forever.
Add a cancel button to allow users to clear the current initialized session from local storage and reload the page to restart the process
> feat: add cancel button into first sign

- package-lock.json
- package.json
The new includes an lazy `ajv` compiler that prevents unnecessary compilation
Issues:
- decentraland/decentraland-connect#43
- decentraland/unity-renderer#4027
> fix: update decentraland-connect with lazy loading

- .github/workflows/main.yml
> fix: `master` branch is no more on renderer

- src/__snapshots__/storybook.test.ts.snap
- src/components/common/Loading/LoadingRender.tsx
Adding muted prop will prevent some browsers block the loading video
> fix: set video as muted

- .github/workflows/set-rollouts.yml
For the transition of the `@dcl/explorer` we set the rollout to prod in 0%, so we're restoring it.
> chore: restore rollout to 100% on .org

- src/components/errors/ErrorContainer.tsx
- src/components/errors/ErrorNetworkMismatch.tsx
- src/kernel-loader/index.ts
How to test it:
- change your network to Mumbai
- connect with your wallet
- when you get the network mismatch error, click on the "switch to mainnet" button
- depending on your wallet you should get different behavior:
- if you are connected with a browser waller you should be prompt to change your network
- otherwise, you should be redirect to the initial page
solves:
- decentraland/unity-renderer#5091
> chore: handle switch to network for non injected wallets - decentraland/unity-renderer#5091

- src/components/auth/LoginContainer.tsx
When connecting to WalletConnect v2, track that instead of sending normal WalletConnect as provider.
> fix: Send wc2 on the login tracking

- src/components/auth/LoginContainer.tsx
- src/integration/featureFlags.ts
- src/state/selectors.ts
The wallet connect flag is unnecessary given that version 1 does not work anymore.
This PRs makes it so version 2 is always used, preventing an unnecessary call to the feature flags server.
> feat: Remove WC2 flag

- src/components/auth/EthConnectAdvice.tsx
- src/components/errors/ErrorNetworkMismatch.tsx
+ Don't disconnect when switching network with WC. This prevented wallets like Zerion from allowing users to switch to the correct network!
> fix: Show proper message when connecting with WC

- src/integration/analytics.ts
After the migration from `play.decentraland.org` to` decentraland.org/play` some metrics has been reported to dev environment instead of production, because the subdomains don't have extra `.` anymore
> fix: wrong segment initalization

- src/components/warning/CatalystWarningContainer.css
This PR changes the z-index of the catalyst confirmation modal so the users can continue the flow with a custom catalyst.
> fix: Show Catalyst warning modal

- src/components/start/Start.container.ts
- src/components/start/Start.tsx
- src/components/start/Start.types.ts
This PR makes the `Start` component wait until the profile has finished loading to prevent showing a user without name or avatar preview.
> fix: Load until the profile is loaded

- src/eth/provider.ts
```
const requestManager = new RequestManager(await connection.getProvider())
const account = (await requestManager.eth_accounts())[0]
```
This code is throwing an error, thus connection.disconnect is not being called.
This change will at least fix the issue of the account not being disconnected after sign out.
> fix: Disconnect not being called

- index.html
- src/components/App.tsx
- src/components/start/Start.container.ts
- src/components/start/Start.css
- src/components/start/Start.tsx
- src/components/start/Start.types.ts
- src/index.tsx
- src/integration/kernel.ts
This PR does the following:
- Removes the root loader which contained an older image of the site
- Moves the `AuthProvider` component closer to the `Start` component, making it possible to sign in into the explorer without doing anything with the RPC provider (we were checking something in the provider).
- Changes the way we compute if the connection was initialized at least once.
> fix: Remove root loader and fix guests

- src/components/warning/NetworkWarning.tsx
- src/eth/provider.ts
- src/kernel-loader/index.ts
This PR fixes the `authenticate` logic of a guest connection.
When passing a `ProviderType === null,` a new provider connection should be created using the decentraland RPCs.
> fix: Get provider for guest and connected wallets

- src/integration/desktop.ts
Add a `?` at the beginning of the deep link
> fix: add '?' to deep link

- src/integration/analytics.ts
- src/integration/browser.ts
- src/integration/desktop.ts
This PR adds two new deep link parameters to the explorer launch action:
- self-preview-builder-collections: which allows users to test their builder collections on the E@.
- dclenv: which allows users to start the E@ using different environments.
> feat: Add new E@ launch parameters
