decentraland/explorer-website

- src/integration/analytics.ts
- src/kernel-loader/index.ts
- src/utils/tracking.ts
It should not affect metrics, because the segment event is being tracked correctly
> chore: report errors to rollbar

- package.json
- src/components/auth/LoginContainer.tsx
- src/components/banners/BannerContainer.tsx
- src/components/banners/BannerContainer.types.ts
- src/components/banners/BannerNotSupported.tsx
- src/components/banners/banners.css
- src/images/banner-close.svg
- src/index.tsx
- src/integration/browser.ts
- src/integration/kernel.ts
- src/state/actions.ts
- src/state/reducers.ts
- src/state/redux.ts
- src/utils/browser.ts
- src/utils/callOnce.ts
- src/utils/tracking.ts
> feat: detect browser

- package-lock.json
- package.json
- src/components/auth/LoginContainer.tsx
A new LoginState was added to the kernel-interface ( https://github.com/decentraland/kernel-interface/commit/017905de24c5267e7146d4152b512205265a63b1 ) but wasn't being taken into account in the explorer website 
Closes #74
> fix: listen to WAITING_RENDERER for the loading status

- src/integration/analytics.ts
resolves [explorer-desktop#131](https://github.com/decentraland/explorer-desktop/issues/131)
> feat: split rollbar between web and desktop

- src/integration/analytics.ts
- src/utils/tracking.ts
> fix: add track options

- package-lock.json
- package.json
- src/eth/provider.ts
- src/kernel-loader/index.ts
Added the tracking of when the user connects the wallet.
Triggers the same event that is used in other dapps (builder, account, market) to have similar data.
> feat(trackConnectWallet): Track connect wallet

- package-lock.json
- package.json
Just connect your wallet using wallet connect, you should see new request pointing to `rpc.decentraland.org`
> feat: new RPC

- src/components/App.css
- src/components/auth/LoginItemNewContainer.css
> fix: background in old EthWallerSelector component and loading

- src/components/errors/ErrorNetworkMismatch.tsx
- src/integration/analytics.ts
- src/integration/queryParamsConfig.ts
- src/integration/url.ts
- src/kernel-loader/index.ts
- src/utils/tracking.ts
This PR limit sources only from `cdn.decentraland.org`
> fix: ensure url on PRD

- src/components/auth/DownloadDesktopToast.tsx
- src/integration/browser.ts
This PR shows the same message we already show on windows but now in mac
> fix: add download message on mac

- src/components/App.tsx
- src/state/selectors.ts
> feat: show download screen if already signed in

- src/integration/analytics.ts
> fix: analytics bug

- public/index.html
> refactor: needless indent

- public/index.html
> fix: error

- src/state/reducers.ts
Fixes decentraland/unity-renderer#3812
> fix: clear errors

- package-lock.json
- package.json
- src/index.tsx
- src/integration/analytics.ts
Fix https://github.com/decentraland/unity-renderer/issues/4345
> feat: add sentry

- src/integration/analytics.ts
> fix: sentry setup

- package-lock.json
- package.json
The version used wasn't working anymore
> fix: Update explorer version

- package-lock.json
- package.json
This PR upgrades the `decentraland-ui` package.
> feat: Upgrade decentraland-ui package

- public/index.html
- public/package.json
- src/index.tsx
- src/integration/analytics.ts
- src/state/selectors.ts
> chore: Remove Rollbar usage

- .github/workflows/set-rollout-by-path-manual.yaml
- .github/workflows/set-rollout-by-path.yaml
This PR adds the path rollout jobs to deploy the play site at `decentraland.org/play`
> feat: Serve play from path

- src/components/App.tsx
- src/components/auth/LoginWithAuthServerPage.css
- src/components/auth/LoginWithAuthServerPage.tsx
- Remove unused import
- Render code expiration countdown
- Jump line on text
> fix: Some Changes

- src/components/auth/LoginWithAuthServerPage.tsx
- src/components/start/Start.tsx
This PR removes the continue button and opens the sign in URL without making the user open it.
> fix: Remove Continue with sign in button

- src/components/App.tsx
- src/components/start/Start.container.ts
Show loading page while requesting feature flags
> fix: loading page while loading ff

- src/components/auth/LoginWithAuthServerPage.css
- src/components/auth/LoginWithAuthServerPage.tsx
This PR adds the capability of logging in as Guest in the Desktop client.
> feat: Add Guest Desktop Login

- .github/workflows/main.yml
- package.json
This PR updates the build process to use node 20.
> fix: Update node 20

- src/components/start/Start.css
- src/components/start/Start.tsx
- src/integration/browser.ts
> fix: add opera to recommended browsers

- .github/workflows/main.yml
- src/integration/desktop.ts
This PR fixes the undefined ipc renderer send method
> fix: Renderer send event

- .github/workflows/main.yml
- vite.config.ts
This PR updates the S3 bucket references
> chore: Update aws references

- package-lock.json
- package.json
This PR updates the packages 
- `decentraland-dapps` to the version `23.14.2`
- `@dcl/schemas` to the version `15.1.2`
> chore: Update the package decentraland-dapps
